[package]
name = "gigatiff"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.102"
clap = { version = "4.6.1", features = ["derive"] }
eframe = "0.34.3"
lcms2 = "6.1.1"
png = "0.18.1"
rayon = "1.12.0"
rfd = "0.17.2"
tiff = "0.11.3"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
panic = "abort"
strip = "symbols"
debug = 0
incremental = false
