[package]
name = "gigatiff-core"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
build = "build.rs"

[features]
default = []
jpeg2000-grok-ffi = ["dep:grokj2k-sys"]

[dependencies]
anyhow.workspace = true
clap = { workspace = true, features = ["derive"] }
grokj2k-sys = { workspace = true, optional = true }
lcms2.workspace = true
png.workspace = true
rayon.workspace = true
tiff.workspace = true
